name: Jupyter
on:
#push:
#branches: [ "main" ]
#pull_request:[ "main" ]
#launch the script (manually)
workflow_dispatch:
#launch GitHub Actions which consists out of one or couple tasks
jobs:
#this script constains one task ("build")
build:
#distributive - ubuntu default
runs-on: ubuntu-latest
#task complete step by step
steps:
- name: Checkout #takes repository $GITHUB_WORKSPACE to give the open permission
uses: actions/checkout@v3
-name: Setup Python #Python download
uses: actions/setup-python@v4.0.0
with:
cache: pip
python-version: '3.7'